spring:
  cloud:
    compatibility-verifier:
      enabled: false
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 60MB
  application:
    name: cwa-log-upload
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:log
    username: sa
    password: ''
  liquibase:
    change-log: classpath:db/changelog.yml
  mvc:
    static-path-pattern: /portal/static/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: log-upload
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: https://verification-iam-c6aebf52.coronawarn.app/auth/realms/cwa
            user-name-attribute: preferred_username
        resourceserver:
          jwt:
            issuer-uri: https://verification-iam-c6aebf52.coronawarn.app/auth/realms/cwa
    filter:
      dispatcher-types: request


server:
  error:
    whitelabel:
      enabled: false
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 14400s

management:
  server:
    port: 8080
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info,health,metrics,prometheus
    jmx:
      exposure:
        include: info,health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

host-header:
  whitelist: localhost:8080

pod:
  ip: 127.0.0.1
  port: 8081

s3:
  accessKey: "minioadmin"
  secretKey: "minioadmin"
  bucketName: "log-upload"
  region:
    name: "eu-de"
    endpoint: "http://localhost:9000"
  proxy:
    enabled: false
    host: ""
    port: -1
log-upload:
  cleanup-cron: 0 0 0 * * *
  log-entity-lifetime: 7
  log-id-byte-length: 10
  keycloak-pw-reset-url: https://localhost:8443/auth/realms/cwa/account/password
els-verify:
  url: https://localhost:8103
  tls:
    enabled: true
    hostname-verify: false
    key-store: /client.jks
    key-store-password: 123456
    trust-store: /truststore.jks
    trust-store-password: 123456
